---
- name: add buster backports | Debian 10
  copy:
    dest: "/etc/apt/sources.list.d/buster-backports.list"
    content: |
      deb http://deb.debian.org/debian buster-backports main contrib
      deb-src http://deb.debian.org/debian buster-backports main contrib
  when:  ansible_distribution  == 'Debian'

- name: add openzfs | Debian 10
  copy:
    dest: "/etc/apt/preferences.d/90_zfs"
    content: |
      Package: libnvpair1linux libuutil1linux libzfs2linux libzpool2linux spl-dkms zfs-dkms zfs-test zfsutils-linux zfsutils-linux-dev zfs-zed
      Pin: release n=buster-backports
      Pin-Priority: 990
  when:  ansible_distribution  == 'Debian'

- name: install linux kernel headers | Debian 10
  apt:
    name:
      - "linux-headers-{{ ansible_kernel }}"
      - linux-image-amd64
      - dpkg-dev
    state: present
  when:  ansible_distribution  == 'Debian'

- name: install zfs and dkms | Debian 10
  apt:
    name:
      - zfs-dkms
      - zfsutils-linux
    update_cache: yes
  when:  ansible_distribution  == 'Debian'

- name: install zfs | Ubuntu 18.04 and up
  package:
    name: zfsutils-linux
    state: latest
  when: ansible_distribution == 'Ubuntu'
  
- name: Add zfs module
  community.general.modprobe:
    name: zfs
    state: present
