---
- name: install Openzfs package | Centos 8
  dnf: 
    name: https://zfsonlinux.org/epel/zfs-release.el8_5.noarch.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_distribution  == 'CentOS' and   ansible_distribution_major_version  == '8'

- name: install epel-release and kernel | Centos 8
  dnf:
    name:
      - epel-release
      - kernel-devel
    state: latest
  when:  ansible_distribution  == 'CentOS' and   ansible_distribution_major_version == '8'

- name: update all packages and caches | CentOS
  package:
    name: "*"
    state: latest
    update_cache: yes
  when:  ansible_distribution  == 'CentOS'

- name: install  Openzfs package | Fedora {{ ansible_distribution_major_version }}
  dnf: 
    name: https://zfsonlinux.org/fedora/zfs-release.fc{{ ansible_distribution_major_version }}.noarch.rpm
    state: present
    disable_gpg_check: yes
  when:  ansible_distribution  == 'Fedora'
  

- name: verify Openzfs gpg key | Fedora {{ ansible_distribution_major_version }}
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
    fingerprint: C93A FFFD 9F3F 7B03 C310 CEB6 A9D5 A1C0 F14A B620
  when:  ansible_distribution  == 'Fedora' or ansible_distribution  == 'Centos'

- name: install kernel devel | Fedora {{ ansible_distribution_major_version }}
  dnf:
    name:
      - kernel-devel
    state: present
  when:  ansible_distribution  == 'Fedora'

- name: install zfs | Fedora or CentOS
  package:
    name: zfs
    state: latest
  when:  ansible_distribution  == 'Fedora' or ansible_distribution == 'CentOS'

- name: Add zfs module
  community.general.modprobe:
    name: zfs
    state: present
