---
- name: install Openzfs package | Centos 8
  command: >-
    dnf install https://zfsonlinux.org/epel/zfs-release.el8_3.noarch.rpm -y
  when: ansible_distribution  == 'CentOS' and   ansible_distribution_major_version  == '8'
  changed_when: false

- name: install epel-release and kernel | Centos 8
  dnf:
    name:
      - epel-release
      - kernel-devel
    state: latest
  when:  ansible_distribution  == 'CentOS' and   ansible_distribution_major_version == '8'

- name: update all packages and caches | CentOS
  package:
    name: "*"
    state: latest
    update_cache: yes
  when:  ansible_distribution  == 'CentOS'

- name: install  Openzfs package | Fedora {{ ansible_distribution_major_version }}
  command: >-
    dnf install https://zfsonlinux.org/fedora/zfs-release.fc{{ ansible_distribution_major_version }}.noarch.rpm -y
  when:  ansible_distribution  == 'Fedora'
  changed_when: false

- name: verify Openzfs gpg key | Fedora {{ ansible_distribution_major_version }}
  rpm_key:
    key: /etc/pki/rpm-gpg/RPM-GPG-KEY-zfsonlinux
    fingerprint: C93A FFFD 9F3F 7B03 C310 CEB6 A9D5 A1C0 F14A B620
  when:  ansible_distribution  == 'Fedora' or ansible_distribution  == 'Centos'

- name: install kernel devel | Fedora {{ ansible_distribution_major_version }}
  dnf:
    name:
      - kernel-devel
    state: present
  when:  ansible_distribution  == 'Fedora'

- name: add buster backports | Debian 10
  copy:
    dest: "/etc/apt/sources.list.d/buster-backports.list"
    content: |
      deb http://deb.debian.org/debian buster-backports main contrib
      deb-src http://deb.debian.org/debian buster-backports main contrib
  when:  ansible_distribution  == 'Debian'

- name: add openzfs | Debian 10
  copy:
    dest: "/etc/apt/preferences.d/90_zfs"
    content: |
      Package: libnvpair1linux libuutil1linux libzfs2linux libzpool2linux spl-dkms zfs-dkms zfs-test zfsutils-linux zfsutils-linux-dev zfs-zed
      Pin: release n=buster-backports
      Pin-Priority: 990
  when:  ansible_distribution  == 'Debian'

- name: install linux kernel headers | Debian 10
  apt:
    name:
      - "linux-headers-{{ ansible_kernel }}"
      - linux-image-amd64
      - dpkg-dev
    state: present
  when:  ansible_distribution  == 'Debian'

- name: install zfs and dkms | Debian 10
  apt:
    name:
      - zfs-dkms
      - zfsutils-linux
    update_cache: yes
  when:  ansible_distribution  == 'Debian'

- name: install zfs | Ubuntu 18.04 and up
  package:
    name: zfsutils-linux
    state: latest
  when: ansible_distribution == 'Ubuntu'

- name: install zfs | Fedora or CentOS
  package:
    name: zfs
    state: latest
  when:  ansible_distribution  == 'Fedora' or ansible_distribution == 'CentOS'

- name: Add zfs module
  community.general.modprobe:
    name: zfs
    state: present
