---
- include_tasks: Install_RedHat.yml
  when: ansible_distribution_family == RedHat

- name: check and create zfs pool
  loop: "{{ zfs_pool }}"
  include_tasks: zpool.yml
  when: item.name is defined

- name: Create and configure Datasets
  loop: "{{ zfs_datasets }}"
  include_tasks: dataset.yml
  when: item.name is defined
