---
- include_tasks: Install_RedHat.yml
  when: ansible_os_family == "RedHat"

- include_tasks: Install_Debian.yml
  when: ansible_os_family == "Debian"

- name: check and create zfs pool
  loop: "{{ zfs_pool }}"
  include_tasks: zpool.yml
  when: item.name is defined

- name: Create and configure Datasets
  loop: "{{ zfs_datasets }}"
  include_tasks: dataset.yml
  when: item.name is defined
